# Generated by Django 4.0.5 on 2022-07-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_MVT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nac', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
